import type { NextPage } from "next";
import Head from "next/head";
import Paragraph from "../components/Paragraph";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col justify-center">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="book">
        <div className="page">
          <div className="subpage">
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
            <Paragraph/>
          </div>
        </div>
        <div className="page">
          <p className="mb-2">Page 2/2</p>
          <div className="subpage"></div>
        </div>
      </div>

    </div>
  );
};

export default Home;
